import os
import json
from datetime import datetime
from logger import log
import tweepy  # pip install tweepy

# ---------------- Build tweet text ----------------
def build_tweet_text(post):
    hashtags = ["#SPXVisuals"]  # Always first

    # Add ticker if present
    if post.get("ticker"):
        hashtags.append(f"#{post['ticker']}")

    # Generic hashtags
    hashtags.extend([
        "#SPX", "#S&P500", "#SP500", "#SAndP500",
        "#Equities", "#Stocks", "#Market", "#StockMarket", "#Investing"
    ])

    # Chart type hashtags
    type_tag_map = {
        "ma": "#SMA #EMA",
        "normalized": "#PriceChart",
        "marketcap": "#MarketCap",
        "pe": "#PE"
    }
    hashtags.append(type_tag_map.get(post["type"], ""))

    hashtags_text = " ".join(hashtags)

    # Determine timeframe / ranges for text
    timeframe_text = ""
    range_text = ""

    if post["type"] == "ma" and post["images"]:
        fname = os.path.basename(post["images"][0])
        if "_" in fname:
            timeframe = fname.split("_")[-1].replace(".png", "")
            timeframe_text = timeframe

    elif post["type"] == "normalized" and post["images"]:
        fname = os.path.basename(post["images"][0])
        timeframe = fname.split("_")[0]
        timeframe_text = timeframe
        # Determine range from filename index
        idx_part = fname.split("_")[1]
        idx_num = int(idx_part.split(".")[0])
        if idx_num == 0:
            range_text = "#1–#10"
        elif idx_num == 1:
            range_text = "#11–#20"
        elif idx_num == 2:
            range_text = "#21–#30"
        elif idx_num == 3:
            range_text = "#31–#40"
        elif idx_num == 4:
            range_text = "#41–#50"

    elif post["type"] == "marketcap" and post["images"]:
        fname = os.path.basename(post["images"][0])
        if "1_10" in fname:
            range_text = "#1–#10"
        elif "11_25" in fname:
            range_text = "#11–#25"
        elif "26_50" in fname:
            range_text = "#26–#50"

    # Build text per type
    if post["type"] == "ma":
        return f"{timeframe_text} - {post['ticker']} SMA & EMA charts 📈 {hashtags_text}"
    elif post["type"] == "normalized":
        return f"{timeframe_text} - Normalized price chart for {range_text} Largest S&P 500 Index Components 📈 {hashtags_text}"
    elif post["type"] == "marketcap":
        return f"Market capitalization distribution chart for {range_text} Largest S&P 500 Index Components 🥧 {hashtags_text}"
    elif post["type"] == "pe":
        pe_type = "Trailing" if "trailing" in post.get("images", [""])[0] else "Forward"
        return f"{pe_type} P/E chart for the 50 Largest S&P 500 stocks 📊 {hashtags_text}"
    else:
        return hashtags_text


# ---------------- Load posts JSON ----------------
def load_posts_json(date=None):
    """Load JSON generated by generate_data.py"""
    if date is None:
        date = datetime.now().strftime("%Y-%m-%d")
    path = f"output/metadata/posts_{date}.json"
    if not os.path.exists(path):
        log(f"No JSON file found for {date} at {path}")
        return []
    with open(path, "r") as f:
        posts = json.load(f)
    log(f"Loaded {len(posts)} posts from JSON")
    return posts


# ---------------- Prepare tweets ----------------
def prepare_posts_for_tweeting(date=None):
    posts = load_posts_json(date)
    tweets = []
    for post in posts:
        text = build_tweet_text(post)
        images = post.get("images", [])
        tweets.append({
            "text": text,
            "images": images
        })
    log(f"Prepared {len(tweets)} tweets")
    return tweets


# ---------------- Post to X / Twitter ----------------
def post_to_x(tweets):
    # Use GitHub Secrets for keys
    api_key = os.environ.get("TWITTER_API_KEY")
    api_key_secret = os.environ.get("TWITTER_API_KEY_SECRET")
    access_token = os.environ.get("TWITTER_ACCESS_TOKEN")
    access_token_secret = os.environ.get("TWITTER_ACCESS_TOKEN_SECRET")

    if not all([api_key, api_key_secret, access_token, access_token_secret]):
        log("Twitter API keys not set in environment variables.")
        return

    auth = tweepy.OAuth1UserHandler(api_key, api_key_secret, access_token, access_token_secret)
    api = tweepy.API(auth)

    for tweet in tweets:
        text = tweet["text"]
        images = tweet["images"]

        # Skip if no images exist
        if not images or not any(os.path.exists(img) for img in images):
            log(f"Skipping tweet because no images found: {text[:50]}...")
            continue

        media_ids = []
        for img in images:
            if os.path.exists(img):
                res = api.media_upload(img)
                media_ids.append(res.media_id_string)
                log(f"Uploaded image {img}")
            else:
                log(f"Image not found: {img}")

        try:
            api.update_status(status=text, media_ids=media_ids)
            log(f"Posted tweet: {text[:50]}...")
        except Exception as e:
            log(f"Failed to post tweet: {text[:50]} | Error: {e}")


# ---------------- Example usage ----------------
if __name__ == "__main__":
    tweets_to_post = prepare_posts_for_tweeting()
    if tweets_to_post:
        post_to_x(tweets_to_post)
    else:
        log("No tweets to post today.")
